### ISSUE TITLE
[violation] sensiolabs insight Test

### ISSUE THREAD

**Issue by danielnv18** [hechoendrupal/DrupalAppConsole#418]
**[in Test/Command/GeneratorPermissionCommandTest.php, line 33](https://github.com/danielnv18/DrupalAppConsole/blob/3efd489c14bea521a6f65d184367be091e2a4fe6/Test/Command/GeneratorPermissionCommandTest.php#L33)**

> This `dir` local variable is declared but never used. You should remove it.

```php
        $cmd->execute($options);
    }

    public function getInteractiveData()
    {
        $dir = sys_get_temp_dir();

        $permissions = [
          [
            'permission' => 'my permission',
            'permission_title' => 'My permission',
```

---------------------

**[in config/translations/console.en.yml, line 434](https://github.com/danielnv18/DrupalAppConsole/blob/3efd489c14bea521a6f65d184367be091e2a4fe6/config/translations/console.en.yml#L434)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
          mode: Site maintenance mode
        messages:
          maintenance-on: Operating in maintenance mode on
          maintenance-off: Operating in maintenance mode off
        errors:
          invalid-mode: Invalid maintance mode
```

---------------------
