### ISSUE TITLE
[insight] code violations report

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalAppConsole#507]
Unused use statement should be avoided - in src/Command/SiteStatusCommand.php, line 10

**[in src/Command/SiteStatusCommand.php, line 10](https://github.com/hechoendrupal/DrupalAppConsole/blob/13e2d470324c353a85fcd1c239891c35237b5b89/src/Command/SiteStatusCommand.php#L10)**

> The class `Symfony\Component\Console\Input\InputArgument` is declared but never used. You should remove the `use` statement.

```php
 */

namespace Drupal\AppConsole\Command;

use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 *  This command provides a view of the current drupal installation.
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d0f089ff-a6e9-4ba4-b353-cb68173c7d90/analyses/43?status=violations)_

Text files should end with a newline character - in config/translations/console.en.yml, line 516

**[in config/translations/console.en.yml, line 516](https://github.com/hechoendrupal/DrupalAppConsole/blob/13e2d470324c353a85fcd1c239891c35237b5b89/config/translations/console.en.yml#L516)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
        group: Group
      messages:
        id: Test Unit ID
        description: Description
        group: Group
        success: The console has been updated to the latest version.
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/d0f089ff-a6e9-4ba4-b353-cb68173c7d90/analyses/43?status=violations)_
