### ISSUE TITLE
[chain] Chain commands execution

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalAppConsole#516]
Taking advantage of this feature Add chain command Helper https://github.com/hechoendrupal/DrupalAppConsole/pull/512  the idea of this is adding a new command that can execute diff commands based on:

* Calling commands by name and take info from defaults see issue https://github.com/hechoendrupal/DrupalAppConsole/issues/515
  $ drupal chain --commands=generate:module, generate:controller

* Reading from a YAML manifest file. 
  $ drupal chain --manifest=PATH_TO_MANIFEST_FILE.yml

I wrote a prototype command, this command executes the `generate:module` & `generate:controller`:
```
<?php
/**
 * @file
 * Contains \Drupal\AppConsole\Command\GeneratorExamplesCommand.
 */
namespace Drupal\AppConsole\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputOption;

class GeneratorExamplesCommand extends ContainerAwareCommand
{
    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
          ->setName('generate:examples')
          ->setDescription($this->trans('commands.generate.example.description'))
        ;
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $generateModuleInputs = [
          '--module' => 'Example module',
          '--machine-name' => 'example',
          '--module-path' => DRUPAL_ROOT . '/modules/custom/',
          '--description' => 'My example module',
          '--core' => '8.x',
          '--package' => 'Test',
          '--test' => false,
          '--controller' => false,
        ];

        $this->getHelper('chain')->addCommand('generate:module', $generateModuleInputs);

        $generateControllerInputs = [
          '--module' => 'example',
          '--class-name' => 'ExampleController',
          '--method-name' => 'index',
          '--route'=>'/index',
          '--services' => 'twig',
        ];

        $this->getHelper('chain')->addCommand('generate:controller', $generateControllerInputs);
    }
}

``` 
And this is the result of executing it:
![console-generate-examples](https://cloud.githubusercontent.com/assets/366275/6719487/2eccb852-cd78-11e4-8451-0eee2999455b.gif)

**Comment by jmolivas** [comment]
This was the final result:
```
$drupal chain --file=/Users/jmolivas/develop/chain-commands.yml
```
Option file must contain a definition like this:
```
# /Users/jmolivas/develop/chain-commands.yml
commands:
  chain:
    - generate:module
    - generate:controller
    - generate:entity:content
  generate:
    module:
      options:
        module: Example module
        machine-name: example
        module-path: /Users/jmolivas/develop/drupal/sites/drupal8.dev/modules/custom/
        description: My example module
        core: 8.x
        package: Test
        controller: false
        dependencies:
        test: false
    controller:
      options:
        module: example
        class-name: ExampleController
        method-name: index
        route: /index
        services: twig
    entity:
      content:
        options:
          module: example
          entity-class: Foo
          entity-name: foo

```

![console-chain](https://cloud.githubusercontent.com/assets/366275/6908761/a22bef22-d6f4-11e4-85c6-7ea1506b85b1.gif)
