### ISSUE TITLE
[chain] Multiple modules in one chain file.

### ISSUE THREAD

**Issue by Jaesin** [hechoendrupal/DrupalAppConsole#582]
Is it possible to generate two different modules using a chain manifest file: 

This manifest will try to create the first module twice.
```yaml
# test.chain.yml
commands:
  chain:
    - generate:module
    - generate:module
  generate:
    module:
      options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    module:
      options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
```

Results in : `Unable to generate the bundle as the target directory ".../modules/sandbox/test_module" is not empty`

**Comment by Jaesin** [comment]
After reading a bit of code and it looks like you are only able to have one of each command because of the way the [ChainCommand](https://github.com/hechoendrupal/DrupalAppConsole/blob/master/src/Command/ChainCommand.php#L80) accesses the options and arguments.

As a result, you can only have one say `generate:service` or `generate:plugin:block` command the way it is.

**Comment by jmolivas** [comment]
Yes you are right, any ideas how to improve it ?

I will take a look at this tomorrow on my flight back.

**Comment by Jaesin** [comment]
I would change the file format to something like: 

```yaml
# test.chain.yml
commands:
  - command: generate:module
    options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    arguments:
        - arg1
        - arg2
  - command: generate:module
      options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
    arguments:
        - arg1
        - arg2
```

Then you can simplify the execute loop: 
```php
/**
 * @file
 * Contains \Drupal\AppConsole\Command\ChainCommand.
 */

$chainData = new Config($file);
$commands = $chainData->get('commands');

foreach ($commands as $command) {
    $moduleInputs = [];
    $arguments = !empty($command['arguments']) ? $command['arguments'] : [];
    $options = !empty($command['options']) ? $command['options'] : [];

    foreach ($arguments as $key => $value) {
        $moduleInputs[$key] = is_null($value) ? '' : $value;
    }

    foreach ($options as $key => $value) {
        $moduleInputs['--' . $key] = is_null($value) ? '' : $value;
    }

    $this->getHelper('chain')
        ->addCommand($command['command'], $moduleInputs, $interactive, $learning);
}
```

**Comment by jmolivas** [comment]
like the idea of removing 
```
chain:
    - generate:module
    - generate:module
```
I just create a PR from your code https://github.com/hechoendrupal/DrupalAppConsole/pull/584

I need to do some test, but like how the code looks like.

**Comment by jmolivas** [comment]
The YAML file is not  valid you can test it here http://www.yamllint.com/ 

Probably doing something like this:
```
commands:
  - command: 
    name: generate:module
    options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    arguments:
        - arg1
        - arg2
  - command: 
      name:
        generate:module
      options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
    arguments:
        - arg1
        - arg2
```

And make changes on the code to read `name` key inside `commands`

**Comment by Jaesin** [comment]
There were some extra spaces.

**Fixed:**
```yaml
# test.chain.yml
commands:
  - command: generate:module
    options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    arguments:
        - arg1
        - arg2
  - command: generate:module
    options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
    arguments:
        - arg1
        - arg2
```

**Comment by Jaesin** [comment]
I pushed an update. I changed `$command['command']` to `$command['name']`.

**Comment by jmolivas** [comment]
@Jaesin do you think make sense ? 

I know I suggested but after reading the YAML file again, it only make sense for me if we nested one extra level at the `command` key like:
```
# chain-commands.yml
commands:
  - command:
      name: generate:module
      options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
      arguments:
        - arg1
        - arg2
  - command:
      name: generate:module
      options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
      arguments:
        - arg1
        - arg2
```
But kinda like your first approach too:
```
# test.chain.yml
commands:
  - command: generate:module
    options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    arguments:
        - arg1
        - arg2
  - command: generate:module
    options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
    arguments:
        - arg1
        - arg2
```

**Comment by jmolivas** [comment]
What I like about the extra nested level is the grouping part but it also requires a new change on the code.

**Comment by Jaesin** [comment]
If you do that, the code looks like: 
```php
$chainData = new Config($file);
$commands = $chainData->get('commands');

foreach ($commands as $command) {
    $moduleInputs = [];
    $arguments = !empty($command['command']['arguments']) ? $command['command']['arguments'] : [];
    $options = !empty($command['command']['options']) ? $command['command']['options'] : [];

    foreach ($arguments as $key => $value) {
        $moduleInputs[$key] = is_null($value) ? '' : $value;
    }

    foreach ($options as $key => $value) {
        $moduleInputs['--' . $key] = is_null($value) ? '' : $value;
    }

    $this->getHelper('chain')
        ->addCommand($command['command']['name'], $moduleInputs, $interactive, $learning);
}
```

I prefer the simpler version myself.

**Comment by jmolivas** [comment]
we can just add after `foreach` statement
```
$command = $command['command']; 
```

**Comment by jmolivas** [comment]
But looks kinda strange, let me think about on my flight back home, but so far looking good

**Comment by Jaesin** [comment]
It's also possible to reference other nodes like: 
```yaml
# test.chain.yml
commands:
  - generate:module: &test_module
      options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
  - generate:module: &test_module_ui
      options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
chain:
  - generate:module: *test_module
  - generate:module: *test_module_ui
```

And then use `$commands = $chainData->get('chain');` but the "anchors" have to come before the references and I think it adds unnecessary complexity.

**Comment by jmolivas** [comment]
I think I do prefer the simpler version myself too.

```
# test.chain.yml
commands:
  - command: generate:module
    options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    arguments:
        - arg1
        - arg2
  - command: generate:module
    options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
    arguments:
        - arg1
        - arg2
```
May we rollback it back sorry for all of the requested changes

**Comment by jmolivas** [comment]
@Jaesin please let me know when the code is updated to merge the PR.

**Comment by Jaesin** [comment]
It's RTM (Ready to Merge).

Tested YAML (Minus the args):
```yaml
# test.chain.yml
commands:
  - command: generate:module
    options:
        module: Test Module
        machine-name: test_module
        module-path: modules/sandbox/
        description: Test Stuff.
        core: 8.x
        package: test
        controller: false
        test: false
    arguments:
        - arg1
        - arg2
  - command: generate:module
    options:
        module: Test Module UI
        machine-name: test_module_ui
        module-path: modules/sandbox/
        description: User Interface for the Test Module.
        core: 8.x
        package: test
        controller: false
        dependencies: test_module
        test: false
    arguments:
        - arg1
        - arg2
```
